// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace AnalyzaRozvrhu.STAG_Classes
{


    public class PlatnostDo
    {

        [JsonProperty("value")]
        public string DateTime { get; set; }
    }

    public class Pracoviste
    {

        [JsonProperty("level")]
        public int Level { get; set; }

        [JsonProperty("cisloPracoviste")]
        public int CisloPracoviste { get; set; }

        [JsonProperty("zkratka")]
        public string Zkratka { get; set; }

        [JsonProperty("nazev")]
        public string Nazev { get; set; }

        [JsonProperty("typPracoviste")]
        public string TypPracoviste { get; set; }


        [JsonProperty("typVedouciho")]
        public string TypVedouciho { get; set; }

        [JsonProperty("nadrazenePracoviste")]
        public string NadrazenePracoviste { get; set; }

        [JsonProperty("platnostDo")]
        public PlatnostDo PlatnostDo { get; set; }
    }

    public class Hierarchie
    {

        [JsonProperty("pracoviste")]
        public Pracoviste[] Pracoviste { get; set; }
    }

}
