// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace AnalyzaRozvrhu.STAG_Classes
{

    public class Student
    {
        public Student()
        {
            Rozvrh = new List<RozvrhovaAkce>();
            
        }

        [JsonProperty("osCislo")]
        public string OsCislo { get; set; }

        
        [JsonProperty("stav")]
        public string Stav { get; set; }


        [JsonProperty("kodSp")]
        public string KodSp { get; set; }

        [JsonProperty("formaSp")]
        public string FormaSp { get; set; }
        
        [JsonProperty("rocnik")]
        public int Rocnik { get; set; }

        [JsonProperty("oborKomb")]
        public string OborKomb { get; set; }

        [JsonProperty("oborIdnos")]
        public string OborIdnos { get; set; }
        
        public List<RozvrhovaAkce> Rozvrh { get; set; }


        public override string ToString()
        {
            return string.Format("'{0}':Rcount({1}),Rocnik({2})",this.OsCislo,this.Rozvrh.Count,this.Rocnik);
        }
        
    }

    public class StudentiResponse
    {

        [JsonProperty("student")]
        public Student[] Student;
    }

}
