// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace AnalyzaRozvrhu.STAG_Classes
{
    /// <summary>
    /// Objektova reprezentace studenta
    /// </summary>
    public class Student
    {
        public Student()
        {
            Rozvrh = new List<RozvrhovaAkce>();
            
        }

        [JsonProperty("osCislo")]
        public string OsCislo { get; set; }

        
        [JsonProperty("stav")]
        public string Stav { get; set; }


        [JsonProperty("kodSp")]
        public string KodSp { get; set; }

        [JsonProperty("formaSp")]
        public string FormaSp { get; set; }
        
        [JsonProperty("rocnik")]
        public int Rocnik { get; set; }

        [JsonProperty("oborKomb")]
        public string OborKomb { get; set; }

        [JsonProperty("oborIdnos")]
        public string OborIdnos { get; set; }
        
        public List<RozvrhovaAkce> Rozvrh { get; set; }


        public override string ToString()
        {
            return string.Format("'{0}':Rcount({1}),Rocnik({2})",this.OsCislo,this.Rozvrh.Count,this.Rocnik);
        }
        

        /// <summary>
        /// TODO:
        /// kolekce SRA studenta, bude se vyuzivat pri zaverecnem rozpoctu
        /// </summary>
        public IEnumerable<SRA> RozvrhSRA { get; set; }

        /// <summary>
        /// TODO!
        /// Sen doplnit samotne podily kateder na vyuce, tohle se bude (mimo jine pouzivat pri exportu do Excel reportu)
        /// Key = Katedra
        /// Value = Procenta <0,100>
        /// Sum(PodilKatedry.Values) = 100!
        /// </summary>
        public Dictionary<string, double> PodilKatedry { get; set; }
    }

    public class StudentiResponse
    {

        [JsonProperty("student")]
        public Student[] Student;
    }

}
