// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace AnalyzaRozvrhu.STAG_Classes
{

    public class Predmet
    {
        public Predmet()
        {
            // Inicializace promennych
            VsechnyAkce = new List<RozvrhovaAkce>();
        }

        [JsonProperty("katedra")]
        public string Katedra { get; set; }


        [JsonProperty("zkratka")]
        public string Zkratka { get; set; }

       

        [JsonProperty("kreditu")]
        public int Kreditu { get; set; }

        
        // Informace pro správnou rozvrhovanost 

        [JsonProperty("jednotekPrednasek")]
        public int JednotekPrednasek { get; set; }

        [JsonProperty("jednotkaPrednasky")]
        public string JednotkaPrednasky { get; set; }

        [JsonProperty("jednotekCviceni")]
        public int JednotekCviceni { get; set; }

        [JsonProperty("jednotkaCviceni")]
        public string JednotkaCviceni { get; set; }

        [JsonProperty("jednotekSeminare")]
        public int JednotekSeminare { get; set; }

        [JsonProperty("jednotkaSeminare")]
        public string JednotkaSeminare { get; set; }


        // Ucitele k predmetu
        [JsonProperty("prednasejici")]
        public string Prednasejici { get; set; }

        [JsonProperty("prednasejiciUcitIdno")]
        public string PrednasejiciUcitIdno { get; set; }

        [JsonProperty("cvicici")]
        public string Cvicici { get; set; }

        [JsonProperty("cviciciUcitIdno")]
        public string CviciciUcitIdno { get; set; }

        [JsonProperty("seminarici")]
        public string Seminarici { get; set; }

        [JsonProperty("seminariciUcitIdno")]
        public string SeminariciUcitIdno { get; set; }

        // Vsechny rozvrhove akce predmetu ktere najdem v rozvrhách
        public List<RozvrhovaAkce> VsechnyAkce { get; private set; }
    }

    public class PredmetResponse
    {

        [JsonProperty("predmetInfo")]
        public Predmet[] PredmetInfo { get; set; }
    }

}
